# Generated by Django 4.0.3 on 2023-03-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='note',
            new_name='title',
        ),
        migrations.AddField(
            model_name='add',
            name='des',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
